#!/bin/sh

mkdir -p ~/terminus && cd ~/terminus
curl -L https://github.com/pantheon-systems/terminus/releases/download/3.1.0/terminus.phar --output terminus
chmod +x terminus
./terminus self:update
ln -s ~/terminus/terminus /usr/local/bin/terminus

terminus self:plugin:install pantheon-systems/terminus-build-tools-plugin
terminus self:plugin:install pantheon-systems/terminus-secrets-manager-plugin
terminus self:plugin:install pantheon-systems/terminus-rsync-plugin
terminus self:plugin:install pantheon-systems/terminus-quicksilver-plugin
terminus self:plugin:install pantheon-systems/terminus-composer-plugin
terminus self:plugin:install pantheon-systems/terminus-drupal-console-plugin
terminus self:plugin:install pantheon-systems/terminus-mass-update
